name: go_board_recognition
repository: https://github.com/justmaker/go-board-recognition

packages:
  - packages/**
  - apps/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- dart analyze .
  test:
    run: melos exec -- flutter test
    packageFilters:
      dirExists: test
