"""
Export model weights as Dart source code.
The model is small enough (77K params) to embed directly.
"""

import torch
import numpy as np
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from train import StoneCNN


def export_dart(pth_path: str, output_path: str):
    model = StoneCNN(3)
    model.load_state_dict(torch.load(pth_path, map_location='cpu', weights_only=True))
    model.eval()

    lines = []
    lines.append("// AUTO-GENERATED — do not edit manually.")
    lines.append("// Generated by tools/training/export_dart_weights.py")
    lines.append("// Model: StoneCNN (77K params)")
    lines.append("")
    lines.append("/// CNN weights for stone classification (black/white/empty).")
    lines.append("class StoneClassifierWeights {")

    # Export each parameter as a flat Float32List literal
    for name, param in model.named_parameters():
        data = param.detach().cpu().numpy().flatten()
        dart_name = name.replace('.', '_')

        # Write shape as comment
        shape = list(param.shape)
        lines.append(f"  /// Shape: {shape}")
        lines.append(f"  static const {dart_name} = <double>[")

        # Write values in chunks
        chunk_size = 12
        for i in range(0, len(data), chunk_size):
            chunk = data[i:i + chunk_size]
            vals = ', '.join(f'{v:.6f}' for v in chunk)
            lines.append(f"    {vals},")

        lines.append("  ];")
        lines.append("")

    lines.append("}")

    with open(output_path, 'w') as f:
        f.write('\n'.join(lines))

    print(f"Exported to {output_path}")
    print(f"File size: {os.path.getsize(output_path) / 1024:.1f} KB")

    # Summary
    total = sum(p.numel() for p in model.parameters())
    print(f"Total parameters: {total:,}")


if __name__ == '__main__':
    pth_path = 'output/model/stone_classifier.pth'
    output_path = '../../packages/core/lib/src/stone_classifier_weights.dart'
    export_dart(pth_path, output_path)
